import { grammer } from "../objects/grammer_types"

export const Grammer:grammer = [
{variable:"<prog>",rightSide:["program","<id>",";","var","<dec-list>","begin","<stat-list>","end"]},
{variable:"<id>",rightSide:["<letter>","<alphaNum>"]},
{variable:"<alphaNum>",rightSide:["<letter>","<alphaNum>"]},
{variable:"<alphaNum>",rightSide:["<digit>","<alphaNum>"]},
{variable:"<alphaNum>",rightSide:"lambda"},
{variable:"<dec-list>",rightSide:["<dec>", ":","<type>",";"]},
{variable:"<dec>",rightSide:["<id>","<moreDec>"]},
{variable:"<moreDec>",rightSide:["<dec>"]},
{variable:"<moreDec>",rightSide:"lambda"},
{variable:"<type>",rightSide:["integer"]},
{variable:"<stat-list>",rightSide:["<stat>", "<moreStat>"]},
{variable:"<moreStat>",rightSide:["<stat-list>"]},
{variable:"<moreStat>",rightSide:"lambda"},
{variable:"<stat>",rightSide:["<write>"]},
{variable:"<stat>",rightSide:["<assign>"]},
{variable:"<write>",rightSide:["show","(","<id>",")",";"]},
{variable:"<assign>",rightSide:["<id>","=","<expr>",";"]},
{variable:"<expr>",rightSide:["<term>","<exprPrime>"]},
{variable:"<exprPrime>",rightSide:["+","<term>","<exprPrime>"]},
{variable:"<exprPrime>",rightSide:["-","<term>","<exprPrime>"]},
{variable:"<exprPrime>",rightSide:"lambda"},
{variable:"<term>",rightSide:["<factor>",]},
{variable:"<termPrime>",rightSide:["*","<factor>","<termPrime>"]},
{variable:"<termPrime>",rightSide:["/","<factor>","<termPrime>"]},
{variable:"<termPrime>",rightSide:"lambda"},
{variable:"<factor>",rightSide:["<id>"]},
{variable:"<factor>",rightSide:["<number>"]},
{variable:"<factor>",rightSide:["(","<expr>",")"]},
{variable:"<number>",rightSide:["<digit>","<moreDigits>"]},
{variable:"<number>",rightSide:["<sign>","<digit>","<moreDigits>"]},
{variable:"<moreDigits>",rightSide:["<digit>","<moreDigits>"]},
{variable:"<moreDigits>",rightSide:"lambda"},
{variable:"<sign>",rightSide:["+"]},
{variable:"<sign>",rightSide:["-"]},
{variable:"<sign>",rightSide:"lambda"},
{variable:"<digit>",rightSide:["0"]},
{variable:"<digit>",rightSide:["1"]},
{variable:"<digit>",rightSide:["2"]},
{variable:"<digit>",rightSide:["3"]},
{variable:"<digit>",rightSide:["4"]},
{variable:"<digit>",rightSide:["5"]},
{variable:"<digit>",rightSide:["6"]},
{variable:"<digit>",rightSide:["7"]},
{variable:"<digit>",rightSide:["8"]},
{variable:"<digit>",rightSide:["9"]},
{variable:"<digit>",rightSide:["a"]},
{variable:"<digit>",rightSide:["b"]},
{variable:"<digit>",rightSide:["c"]},
{variable:"<digit>",rightSide:["d"]},
{variable:"<digit>",rightSide:["e"]}];